### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Phelipe** [cdsousa/Robotics.jl#2]
Can you explain how is possible use the package? I do not understood how to use in a generic robot manipulator.
Thank you!

**Comment by cdsousa** [comment]
I'm sorry but I won't probably have time to further document this...
The best one can do is to read the tests, and then the source itself.
I'll answer specific questions. 

This was something I wrote mainly for myself, but decided it must be open source anyway.
I provide this as a non-registered Julia package and I'm available to free this name if someone wants to use it in a more serious project.

**Comment by Phelipe** [comment]
Ok, thank you! I will see the tests.
